##
 # A reusable Gradle build workflow for testing for breaking changes.
 #
 # This workflow can be called from workflow jobs in other repos with:
 #  `uses: cameron-thomson-bsl/github-workflows/.github/workflows/test-gradle-build.yml@develop`
 #
 # See https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

name: Reusable build with Gradle workflow

on:
  # This workflow will run when called by another workflow.
  workflow_call:
    inputs:
      github-ref-name:
        description: "The short ref name of the branch or tag that triggered the workflow run."
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits to ensure `git describe` returns correct version.
          fetch-depth: 0
      - name: Fix tag
        # Workaround actions/checkout bug. See:
        # - https://github.com/actions/checkout/issues/290
        # - https://github.com/actions/checkout/issues/882
        if: github.ref_type == 'tag'
        run: git fetch -fv origin tag "${GITHUB_REF_NAME}"
        env:
          GITHUB_REF_NAME: ${{ inputs.github-ref-name }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"
      - name: Execute Gradle build
        run: ./gradlew build
